-- 1
SELECT * from ANIMAL_INS order by ANIMAL_ID asc

-- 2
SELECT NAME,DATETIME from ANIMAL_INS order by ANIMAL_ID desc

-- 3
SELECT ANIMAL_ID,NAME from ANIMAL_INS where INTAKE_CONDITION="Sick"

-- 4
SELECT ANIMAL_ID,NAME from ANIMAL_INS where INTAKE_CONDITION!="Aged"

-- 5
SELECT ANIMAL_ID,NAME from ANIMAL_INS order by ANIMAL_ID asc

--6
SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS ORDER BY NAME ASC, DATETIME DESC

-- 7
SELECT NAME from ANIMAL_INS order by DATETIME asc limit 1
